config/routes.rb
Dpwwork::Application.routes.draw do
  
  get "models/index"

  resources :talklinktypes

  resources :talklinks

  resources :publinktypes

  resources :publinks

  resources :pubtypes

  mount Ckeditor::Engine => '/ckeditor'

  resources :static_pages

  devise_for :users

  resources :categories

  resources :talks do
    get :bydate, :on => :collection
  end

  resources :publications do
    get :bydate, :on => :collection
    get :bytype, :on => :collection
    get :bycategory, :on => :collection
  end

  match "/home" => "static_pages#home", :as => :home
  match "/courses" => "static_pages#courses", :as => :courses
  match "/contact" => "static_pages#contact", :as => :contact

  root :to => "static_pages#home"

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  attr_accessible :content, :name
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_filter :authenticate_user!, :except => [:home, :courses, :contact]

  def home
    @publications = Publication.find(:all, :order => "pub_date DESC", :limit => 3)
    @talks = Talk.find(:all, :order => "talk_date DESC", :limit => 3)
    @content = StaticPage.find_by_name("home").content
  end

  def courses
    @content = StaticPage.find_by_name("courses").content
  end

  def contact
    @content = StaticPage.find_by_name("contact").content
  end

  # GET /static_pages
  # GET /static_pages.json
  def index
    @static_pages = StaticPage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @static_pages }
    end
  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
    @static_page = StaticPage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @static_page }
    end
  end

  # GET /static_pages/new
  # GET /static_pages/new.json
  def new
    @static_page = StaticPage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @static_page }
    end
  end

  # GET /static_pages/1/edit
  def edit
    @static_page = StaticPage.find(params[:id])
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(params[:static_page])

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: 'Static page was successfully created.' }
        format.json { render json: @static_page, status: :created, location: @static_page }
      else
        format.html { render action: "new" }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /static_pages/1
  # PUT /static_pages/1.json
  def update
    @static_page = StaticPage.find(params[:id])

    respond_to do |format|
      if @static_page.update_attributes(params[:static_page])
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page = StaticPage.find(params[:id])
    @static_page.destroy

    respond_to do |format|
      format.html { redirect_to static_pages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.cktext_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<% content_for :pagename, "contact" %>

<div id="content">

<%= raw(@content) %>
  
</div>

app/views/static_pages/courses.html.erb
<% content_for :pagename, "courses" %>

<div id="content">

<%= raw(@content) %>

</div>

app/views/static_pages/edit.html.erb
<h1>Editing static_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/home.html.erb
<% content_for :pagename, "home" %>

<div id="content">
  
<div id="recentbar">
<div class="recent">
<h1>Recent Publications</h1>
<div class="pubs">
<ul>
<%= render(@publications) %>
</ul>
</div>
</div>
<div class="recent">
<h1>Recent Talks</h1>
<div class="talks">
<ul>
<%= render(@talks) %>
</ul>
</div>
</div>
</div>


<%= raw(@content) %>

</div>

app/views/static_pages/index.html.erb
<h1>Listing static_pages</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @static_pages.each do |static_page| %>
  <tr>
    <td><%= static_page.name %></td>
    <td><%= link_to 'Show', static_page %></td>
    <td><%= link_to 'Edit', edit_static_page_path(static_page) %></td>
    <td><%= link_to 'Destroy', static_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Static page', new_static_page_path %>

app/views/static_pages/new.html.erb
<h1>New static_page</h1>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @static_page.name %>
</p>

<p>
  <b>Content:</b>
  <%= raw(@static_page.content) %>
</p>


<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>