config/routes.rb
Dpwwork::Application.routes.draw do
  
  get "models/index"

  resources :talklinktypes

  resources :talklinks

  resources :publinktypes

  resources :publinks

  resources :pubtypes

  mount Ckeditor::Engine => '/ckeditor'

  resources :static_pages

  devise_for :users

  resources :categories

  resources :talks do
    get :bydate, :on => :collection
  end

  resources :publications do
    get :bydate, :on => :collection
    get :bytype, :on => :collection
    get :bycategory, :on => :collection
  end

  match "/home" => "static_pages#home", :as => :home
  match "/courses" => "static_pages#courses", :as => :courses
  match "/contact" => "static_pages#contact", :as => :contact

  root :to => "static_pages#home"

end

app/models/publication.rb
class Publication < ActiveRecord::Base
  attr_accessible :bibtex, :html_authors, :html_reference, :html_title, :pub_date, :pubtype_id, :publinks_attributes, :category_ids

  has_many :publinks
  has_and_belongs_to_many :categories
  belongs_to :pubtype

  accepts_nested_attributes_for :publinks, :allow_destroy => true
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController

before_filter :authenticate_user!, :except => [:bydate, :bytype, :bycategory]
  
  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publications }
    end
  end

  def bydate
    @publications = Publication.find(:all, :order => "pub_date DESC")
    @pubyears = @publications.group_by {|t| t.pub_date.year}
  end

  def bytype
    @publications = Publication.find(:all, :order => "pubtype_id, pub_date DESC")
    @pubtypes = @publications.group_by {|t| t.pubtype.name}
  end

  def bycategory
    @categories = Category.find(:all, :order => "name")
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
    @publication = Publication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @publication }
    end
  end

  # GET /publications/new
  # GET /publications/new.json
  def new
    @publication = Publication.new
    @categories = Category.find(:all, :order => "name")

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @publication }
    end
  end

  # GET /publications/1/edit
  def edit
    @publication = Publication.find(params[:id])
    @categories = Category.find(:all, :order => "name")
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(params[:publication])
    @categories = Category.find(:all, :order => "name")
    if params[:add_link]
      @publication.publinks.build
      render :action => 'new'
    elsif params[:remove_link]
      render :action => 'new'
    else
      respond_to do |format|
        if @publication.save
          format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
          format.json { render json: @publication, status: :created, location: @publication }
        else
          format.html { render action: "new" }
          format.json { render json: @publication.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /publications/1
  # PUT /publications/1.json
  def update
    @publication = Publication.find(params[:id])
    @categories = Category.find(:all, :order => "name")
    if params[:add_link]
      unless params[:publication][:publinks_attributes].blank?
        for attribute in params[:publication][:publinks_attributes]
          @publication.publinks.build(attribute.last.except(:_destroy)) unless attribute.last.has_key?(:id)
        end
      end
      @publication.publinks.build
      render :action => 'edit'
    elsif params[:remove_link]
      removed_links = params[:publication][:publinks_attributes].collect { |i, att| att[:id] if (att[:id] && att[:_destroy].to_i == 1) }
      Publink.delete(removed_links)
      flash[:notice] = "Links removed."
      for attribute in params[:publication][:publinks_attributes]
        @publication.publinks.build(attribute.last.except(:_destroy)) if (!attribute.last.has_key?(:id) && attribute.last[:_destroy].to_i == 0)
      end
      render :action => 'edit'
    else
      respond_to do |format|
        if @publication.update_attributes(params[:publication])
          format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @publication.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url }
      format.json { head :no_content }
    end
  end
end

app/views/publications/_form.html.erb
<%= form_for(@publication) do |f| %>
  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :html_title %><br />
    <%= f.text_field :html_title %>
  </div>
  <div class="field">
    <%= f.label :html_authors %><br />
    <%= f.text_field :html_authors %>
  </div>
  <div class="field">
    <%= f.label :html_reference %><br />
    <%= f.text_field :html_reference %>
  </div>
  <div class="field">
    <%= f.label :pub_date %><br />
    <%= f.date_select(:pub_date, :start_year => 1990) %>
  </div>
  <div class="field">
    <%= f.label :pubtype_id %><br />
    <%= collection_select(:publication, :pubtype_id, Pubtype.all, :id, :name, :prompt => true) %>
  </div>
  <div class="field">
    <%= f.label :bibtex %><br />
    <%= f.text_area :bibtex %>
  </div>
  <div class="field">
    <%= f.label :categories %><br />
    <% for category in @categories do %>
      <%= check_box_tag "publication[category_ids][]", category.id, @publication.categories.include?(category) %>
      <%= category.name %><br/>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :publinks %><br />
    <%= f.fields_for :publinks do |pl| %>
      <%= pl.collection_select(:publinktype_id, Publinktype.all, :id, :name, :include_blank => true) %>
      <%= pl.label :url %>
      <%= pl.text_field :url %>
      <%= pl.check_box :_destroy %>
      <%= pl.label :_destroy, 'delete' %><br />
    <% end %>
  <div class="actions">
    <%= f.submit "Add link", :name => "add_link" %>
    <%= f.submit "Delete checked links", :name => "remove_link" %><br /><br />
    <%= f.submit %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<li>
<% unless publication.publinks.empty? %>
  <%= link_to(sanitize(publication.html_title), publication.publinks.first.url) %>
<% else %>
 <%= sanitize publication.html_title %>
<% end %>
<p><%= sanitize publication.html_authors %></p>
<p><%= sanitize publication.html_reference %></p>
<% unless publication.publinks.empty? %>
  <ul>
    <% for publink in publication.publinks %>
      <li><%= link_to(publink.publinktype.name, publink.url) %></li>  
    <% end %>
  </ul>
<% end %>
</li>

app/views/publications/bycategory.html.erb
<% content_for :pagename, "pubs" %>

<div id="bycategory">
<%= render "shared/pubnavbar" %>
</div>


<div id="content">
<h1 id="pubheader">Publications</h1>
<div class="pubs">


<% for category in @categories %>
  <% if !category.publications.empty? %>
    <h2><%= category.name %></h2> <hr />
    <ul>
      <% sortedpubs = category.publications.sort { |a, b| b.pub_date <=> a.pub_date } %>
      <%= render(sortedpubs) %>
    </ul>
  <% end %>
<% end %>
</div>
</div>

app/views/publications/bydate.html.erb
<% content_for :pagename, "pubs" %>

<div id="bydate">
<%= render "shared/pubnavbar" %>
</div>

<div id="content">
<h1 id="pubheader">Publications</h1>
  
<div class="pubs">

<% @pubyears.each do |year, publications| %>
<h2><%= year %></h2><hr />
    
    <ul>
    <%= render(publications) %>
    </ul>
<% end %>

</div>
</div>

app/views/publications/bytype.html.erb
<% content_for :pagename, "pubs" %>

<div id="bytype">
<%= render "shared/pubnavbar" %>
</div>

<div id="content">
<h1 id="pubheader">Publications</h1> 



<div class="pubs">

<% @pubtypes.each do |typename, publications| %>
<h2><%= typename %></h2><hr />
    
    <ul>
    <%= render(publications) %>
    </ul>
<% end %>

</div>
</div>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render 'form' %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<h1>Listing publications</h1>

<table>
  <tr>
    <th>Pub date</th>
    <th>Bibtex</th>
    <th>Pubtype</th>
    <th>Html title</th>
    <th>Html authors</th>
    <th>Html reference</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @publications.each do |publication| %>
  <tr>
    <td><%= publication.pub_date %></td>
    <td><%= publication.bibtex %></td>
    <td><%= publication.pubtype_id %></td>
    <td><%= publication.html_title %></td>
    <td><%= publication.html_authors %></td>
    <td><%= publication.html_reference %></td>
    <td><%= link_to 'Show', publication %></td>
    <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
    <td><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Publication', new_publication_path %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render 'form' %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pub date:</b>
  <%= @publication.pub_date %>
</p>

<p>
  <b>Bibtex:</b>
  <%= @publication.bibtex %>
</p>

<p>
  <b>Pubtype:</b>
  <%= @publication.pubtype_id %>
</p>

<p>
  <b>Html title:</b>
  <%= @publication.html_title %>
</p>

<p>
  <b>Html authors:</b>
  <%= @publication.html_authors %>
</p>

<p>
  <b>Html reference:</b>
  <%= @publication.html_reference %>
</p>


<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>