config/routes.rb
Dpwwork::Application.routes.draw do
  
  get "models/index"

  resources :talklinktypes

  resources :talklinks

  resources :publinktypes

  resources :publinks

  resources :pubtypes

  mount Ckeditor::Engine => '/ckeditor'

  resources :static_pages

  devise_for :users

  resources :categories

  resources :talks do
    get :bydate, :on => :collection
  end

  resources :publications do
    get :bydate, :on => :collection
    get :bytype, :on => :collection
    get :bycategory, :on => :collection
  end

  match "/home" => "static_pages#home", :as => :home
  match "/courses" => "static_pages#courses", :as => :courses
  match "/contact" => "static_pages#contact", :as => :contact

  root :to => "static_pages#home"

end

app/models/talk.rb
class Talk < ActiveRecord::Base
  attr_accessible :institution, :location, :talk_date, :title

  has_many :talklinks
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController

before_filter :authenticate_user!, :except => [:bydate]

  # GET /talks
  # GET /talks.json
  def index
    @talks = Talk.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @talks }
    end
  end

  def bydate
    @talks = Talk.find(:all, :order => "talk_date DESC")
    @talkyears = @talks.group_by {|t| t.talk_date.year}
  end

  # GET /talks/1
  # GET /talks/1.json
  def show
    @talk = Talk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @talk }
    end
  end

  # GET /talks/new
  # GET /talks/new.json
  def new
    @talk = Talk.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @talk }
    end
  end

  # GET /talks/1/edit
  def edit
    @talk = Talk.find(params[:id])
  end

  # POST /talks
  # POST /talks.json
  def create
    @talk = Talk.new(params[:talk])
    if params[:add_link]
      @talk.talklinks.build
      render :action => 'new'
    elsif params[:remove_link]
      render :action => 'new'
    else
      respond_to do |format|
        if @talk.save
          format.html { redirect_to @talk, notice: 'Talk was successfully created.' }
          format.json { render json: @talk, status: :created, location: @talk }
        else
          format.html { render action: "new" }
          format.json { render json: @talk.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /talks/1
  # PUT /talks/1.json
  def update
    @talk = Talk.find(params[:id])
    if params[:add_link]
      unless params[:talk][:talklinks_attributes].blank?
        for attribute in params[:talk][:talklinks_attributes]
          @talk.talklinks.build(attribute.last.except(:_destroy)) unless attribute.last.has_key?(:id)
        end
      end
      @talk.talklinks.build
      render :action => 'edit'
    elsif params[:remove_link]
      removed_links = params[:talk][:talklinks_attributes].collect { |i, att| att[:id] if (att[:id] && att[:_destroy].to_i == 1) }
      Talklink.delete(removed_links)
      flash[:notice] = "Links removed."
      for attribute in params[:talk][:talklinks_attributes]
        @talk.talklinks.build(attribute.last.except(:_destroy)) if (!attribute.last.has_key?(:id) && attribute.last[:_destroy].to_i == 0)
      end
      render :action => 'edit'
    else
      respond_to do |format|
        if @talk.update_attributes(params[:talk])
          format.html { redirect_to @talk, notice: 'Talk was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @talk.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /talks/1
  # DELETE /talks/1.json
  def destroy
    @talk = Talk.find(params[:id])
    @talk.destroy

    respond_to do |format|
      format.html { redirect_to talks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/talks/_form.html.erb
<%= form_for(@talk) do |f| %>
  <% if @talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talk.errors.count, "error") %> prohibited this talk from being saved:</h2>

      <ul>
      <% @talk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :institution %><br />
    <%= f.text_field :institution %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :talk_date %><br />
    <%= f.date_select :talk_date %>
  </div>
  <div class="field">
    <%= f.label :talklinks %><br />
    <%= f.fields_for :talklinks do |pl| %>
      <%= pl.collection_select(:talklinktype_id, Talklinktype.all, :id, :name, :include_blank => true) %>
      <%= pl.label :url %>
      <%= pl.text_field :url %>
      <%= pl.check_box :_destroy %>
      <%= pl.label :_destroy, 'delete' %><br />
    <% end %>
  <div class="actions">
    <%= f.submit "Add link", :name => "add_link" %>
    <%= f.submit "Delete checked links", :name => "remove_link" %><br /><br />
    <%= f.submit %>
  </div>
<% end %>

app/views/talks/_talk.html.erb
<li>
<% unless talk.talklinks.empty? %>
  	<%= link_to(sanitize(talk.title), talk.talklinks.first.url) %>
<% else %>
 	<%= sanitize talk.title %>
<% end %>
<p><%= sanitize talk.institution + ". " + talk.location + ". " %></p>
<% unless talk.note.empty? %>
	<p><%= sanitize talk.note + ". " %>
<% end %>
<p> <%= talk.talk_date.strftime("%B %d, %Y") + ". " %></p>
<% unless talk.talklinks.empty? %>
  <ul>
    <% for talklink in talk.talklinks %>
      <li><%= link_to(talklink.talklinktype.name, talklink.url) %></li>  
    <% end %>
  </ul>
<% end %>
</li>

app/views/talks/bydate.html.erb
<% content_for :pagename, "talks" %>

<div id="content">
<h1 id="talkheader">Talks</h1>
  
<div class="talks">

<% @talkyears.each do |year, talks| %>
<h2><%= year %></h2><hr />
    
    <ul>
    <%= render(talks) %>
    </ul>
<% end %>

</div>
</div>

app/views/talks/edit.html.erb
<h1>Editing talk</h1>

<%= render 'form' %>

<%= link_to 'Show', @talk %> |
<%= link_to 'Back', talks_path %>

app/views/talks/index.html.erb
<h1>Listing talks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Institution</th>
    <th>Location</th>
    <th>Talk date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @talks.each do |talk| %>
  <tr>
    <td><%= talk.title %></td>
    <td><%= talk.institution %></td>
    <td><%= talk.location %></td>
    <td><%= talk.talk_date %></td>
    <td><%= link_to 'Show', talk %></td>
    <td><%= link_to 'Edit', edit_talk_path(talk) %></td>
    <td><%= link_to 'Destroy', talk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Talk', new_talk_path %>

app/views/talks/new.html.erb
<h1>New talk</h1>

<%= render 'form' %>

<%= link_to 'Back', talks_path %>

app/views/talks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @talk.title %>
</p>

<p>
  <b>Institution:</b>
  <%= @talk.institution %>
</p>

<p>
  <b>Location:</b>
  <%= @talk.location %>
</p>

<p>
  <b>Talk date:</b>
  <%= @talk.talk_date %>
</p>


<%= link_to 'Edit', edit_talk_path(@talk) %> |
<%= link_to 'Back', talks_path %>